# -*- coding: utf-8 -*-
"""I mage procesiing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_HnjO5S31F-cwgsYm73dbs1qMrDkqwAi
"""

!wget 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP4uvGJj4OMKfux3aQxGhdVm-1CiaL4j28jA&s'

#image module
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

#loading an image through matplotlib library
img=mpimg.imread('/content/girl.jpeg')

type(img)

print(img.shape)

print(img)

#displating the image from numpy arrayimg
img_array=plt.imshow(img)